# Generated by Django 5.2.13 on 2026-04-24 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказа'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='defect_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий к браку'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='material_width',
            field=models.DecimalField(choices=[(1.2, '1.2 м'), (1.26, '1.26 м'), (1.37, '1.37 м'), (1.5, '1.5 м'), (1.6, '1.6 м'), (0.0, 'Не применимо / Штучно')], decimal_places=2, default=0.0, max_digits=5, verbose_name='Ширина материала'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('printed', 'Напечатан'), ('ready', 'Готов'), ('issued', 'Выдан')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='height',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Высота (м)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='width',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Ширина (м)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='calc_type',
            field=models.CharField(choices=[('per_m2', 'За квадратный метр'), ('per_unit', 'За штуку')], max_length=10, verbose_name='Тип расчета'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
