# Generated by Django 5.2.13 on 2026-04-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='material_width',
            field=models.DecimalField(choices=[(1.2, '1.2 м'), (1.26, '1.26 м'), (1.37, '1.37 м'), (1.5, '1.5 м'), (1.6, '1.6 м'), (0.0, 'Штучно / Другое')], decimal_places=2, default=0.0, max_digits=5, verbose_name='Ширина материала'),
        ),
    ]
