# Generated by Django 5.2.13 on 2026-04-24 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_material_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название материала')),
                ('material_type', models.CharField(choices=[('roll', 'Рулон (погонные метры)'), ('unit', 'Штучный товар')], default='roll', max_length=10, verbose_name='Тип')),
                ('width', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ширина рулона (м)')),
                ('total_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Остаток (м/шт)')),
                ('min_stock', models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='Критический остаток')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Склад материалов',
            },
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='defect_comment',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='material_width',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_deducted',
            field=models.BooleanField(default=False, verbose_name='Списано со склада'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('ready', 'Готов'), ('issued', 'Выдан')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.material', verbose_name='Материал со склада'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.material', verbose_name='Материал по умолчанию'),
        ),
    ]
