# Generated by Django 5.2.13 on 2026-04-24 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_material_remove_orderitem_defect_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена закупа'),
        ),
        migrations.CreateModel(
            name='MaterialLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('action_type', models.CharField(choices=[('in', 'Приход (пополнение)'), ('out', 'Расход (заказ)'), ('defect', 'Расход (брак/перепечатка)'), ('return', 'Возврат на склад')], max_length=10, verbose_name='Тип действия')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Комментарий/Номер заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='orders.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Лог движения материала',
                'verbose_name_plural': 'История склада',
            },
        ),
    ]
