# Generated by Django 5.2.13 on 2026-04-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_material_purchase_price_materiallog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название материала')),
                ('material_type', models.CharField(choices=[('roll', 'Рулон'), ('unit', 'Штука')], default='roll', max_length=10, verbose_name='Тип')),
                ('width', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ширина рулона (м)')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена закупа')),
            ],
            options={
                'verbose_name': 'Шаблон материала',
                'verbose_name_plural': 'Шаблоны материалов',
            },
        ),
    ]
