# Generated by Django 5.2.13 on 2026-04-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_materialtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='height',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Высота (м)'),
        ),
        migrations.AddField(
            model_name='materialtemplate',
            name='height',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Высота (м)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('roll', 'Рулон (погонные метры)'), ('unit', 'Лист/Штука')], default='roll', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='material',
            name='total_stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='material',
            name='width',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Ширина (м)'),
        ),
        migrations.AlterField(
            model_name='materialtemplate',
            name='material_type',
            field=models.CharField(choices=[('roll', 'Рулон'), ('unit', 'Лист/Штука')], default='roll', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='materialtemplate',
            name='width',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Ширина (м)'),
        ),
    ]
